Adding colouring to the errors and success
Signed-off-by: gokulks97 <gokulks@progress.com>

diff --git a/update_cookbook b/update_cookbook
--- a/update_cookbook
+++ b/update_cookbook
@@ -2,7 +2,7 @@
 profile_name=$1
 log_level=0
 HOME_DIR=~
-[[ $profile_name == "" ]] && echo "Profile Name not provided" && exit 1
+[[ $profile_name == "" ]] && echo -e "\033[31mProfile Name not provided\033[0m" >&2 && exit 1
 
 git_cb="${HOME_DIR}/Documents/code_repo/chef_repos/compliance-remediation-2022/improvised_remediation/${profile_name}"
 if [ -d $git_cb ]
@@ -13,12 +13,12 @@ then
 	if [ -d $workspace_cb ]
 	then
 		[[ $log_level != 0 ]] && echo "Cookbook found"
-		rm -rf $workspace_cb && echo "Deleted ${profile_name} : WORKSPACE"
-		cp -rf $git_cb $workspace_folder && echo "Copied ${profile_name} : LOCAL GIT REPO"
+		rm -rf $workspace_cb && echo "\033[32mDeleted ${profile_name} : WORKSPACE\033[0m"
+		cp -rf $git_cb $workspace_folder && echo "\033[32mCopied ${profile_name} : LOCAL GIT REPO\033[0m"
 	else
 		[[ $log_level != 0 ]] && echo "Cookbook not found"
 		cp -rf $git_cb $workspace_folder && echo "Copied ${profile_name} : LOCAL GIT REPO"
 	fi
 else
-	echo "directory not found.. Maybe local git repo is not found"
+	echo -e "\033[31mdirectory not found.. Maybe local git repo is not found\033[0m" >&2
 fi
